<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Yggdrasil.SharedKernel\Yggdrasil.SharedKernel.csproj" />
    <ProjectReference Include="..\Yggdrasil.Tyr.Core\Yggdrasil.Tyr.Core.csproj" />
    <ProjectReference Include="..\Yggdrasil.Tyr.UseCases\Yggdrasil.Tyr.UseCases.csproj" />
  </ItemGroup>

</Project>
